data:
    name: megadepth
    seed: 42
    preprocessing:
        resize: 1024
        side: long
        square_pad: True
    train_split: train_scenes_clean.txt
    num_overlap_bins: 3
    train_num_per_scene: 400
    val_split: valid_scenes_clean.txt
    val_pairs: valid_pairs.txt
    min_overlap: 0.1
    max_overlap: 1.0
    read_depth: true
    read_image: true
    batch_size: 12
    num_workers: 1
    load_features:
        do: false
        path: exports/megadepth-undist-depth-r1024_pycolmap_SIFTGPU-nms3-fixed-k2048/{scene}.h5
        padding_length: 2048
        padding_fn: pad_local_features
        data_keys: ["keypoints", "keypoint_scores", "descriptors", "oris", "scales"]
features_model:
    name: two_view_pipeline
    freeze: True
    extractor:
        name: extractors.superpoint_open
        max_num_keypoints: 2048
        force_num_keypoints: True
        detection_threshold: -1
        nms_radius: 3
        trainable: False
    matcher:
        name: matchers.lightglue
        features: superpoint
        filter_threshold: 0.0
        flash: false
        checkpointed: true
        weights: weights/superpoint_lightglue.pth
    ground_truth:
        name: matchers.depth_matcher
        th_positive: 3
        th_negative: 5
        th_epi: 5
    allow_no_extract: True
photo_vo:
    name: photo_vo
    model:
      patch_size: 16
      dim_emb: 64
      num_matches: 50
      loss_weights:
        photometric: 0.0
        pose: 1.0
        match: 0.0
train:
    epochs: 20
    save_every_iter: -1
    log_every_iter: 100
    eval_every_iter: 1000
    lr: 1e-4
    load_experiment: exp21
