data:
    name: megadepth
    preprocessing:
        resize: 1024
        side: long
        square_pad: True
    train_split: train_scenes_tests.txt
    train_num_per_scene: 5
    val_split: valid_scenes_tests.txt
    val_pairs: valid_pairs.txt
    min_overlap: 0.6
    max_overlap: 1.0
    num_overlap_bins: 1
    read_depth: true
    read_image: true
    batch_size: 1
    num_workers: 8
    load_features:
        do: false  # enable this if you have cached predictions
        path: exports/megadepth-undist-depth-r1024_pycolmap_SIFTGPU-nms3-fixed-k2048/{scene}.h5
        padding_length: 2048
        padding_fn: pad_local_features
        data_keys: ["keypoints", "keypoint_scores", "descriptors", "oris", "scales"]
features_model:
    name: two_view_pipeline
    extractor:
        name: extractors.superpoint_open
        max_num_keypoints: 2048
        force_num_keypoints: True
        detection_threshold: -1
        nms_radius: 3
        trainable: False
    matcher:
        name: matchers.lightglue
        features: superpoint
        filter_threshold: 0.1
        flash: false
        checkpointed: true
        weights: weights/superpoint_lightglue.pth

    ground_truth:
        name: matchers.depth_matcher
        th_positive: 3
        th_negative: 5
        th_epi: 5
    allow_no_extract: True
photo_vo:
    name: photo_vo
    model:
        patch_size: 16
        dim_image_emb: 512
train:
    seed: 0
    epochs: 5
    log_every_iter: 100
    eval_every_iter: 1000
    lr: 1e-4
    lr_schedule:
        start: 30
        type: exp
        on_epoch: true
        exp_div_10: 10
    dataset_callback_fn: sample_new_items
    plot: [5, 'gluefactory.visualization.visualize_batch.make_match_figures']
