data:
  seed: 42
  datasets_names:
    - kitti
    - queenscamp
  kitti:
    data_path: /home/hudson/Desktop/Unicamp/datasets/kitti #/home/hudson/data/kitti
    size: [640, 640]
    max_skip: 0
    train_sequences: 
      - "08"
    val_sequences:
      - "03"
  queenscamp:
    data_path: /home/hudson/Desktop/Unicamp/datasets/queenscamp
    size: [640, 640]
    max_skip: 0
    train_sequences: 
      - "16"
    val_sequences:
      - "12"
  batch_size: 1  
features_model:
    name: two_view_pipeline
    freeze: True
    extractor:
        name: extractors.superpoint_open
        max_num_keypoints: 2048
        force_num_keypoints: True
        detection_threshold: -1
        nms_radius: 3
        trainable: False
    matcher:
        name: matchers.lightglue
        features: superpoint
        filter_threshold: 0.0
        flash: false
        checkpointed: true
        weights: weights/superpoint_lightglue.pth
    ground_truth:
        name: matchers.depth_matcher
        th_positive: 3
        th_negative: 5
        th_epi: 5
    allow_no_extract: True
vit:
  freeze: True
  unfreeze_last: 4
  patch_size: 16
  dim_emb: 384
  heads: 6
  image_size: [640, 640]
  depth: 12
  pretrained: True
  pretrained_weights: 'best_model_kitti_qc_tartan.pth'
photo_vo:
    name: photo_vo
    model:
      patch_size: 16
      dim_emb: 384
      num_matches: 128
      loss_weights:
        photometric: 0.0
        pose: 1.0
        match: 0.0
train:
    seed: 0
    epochs: 10
    save_every_iter: 2
    log_every_iter: 2
    eval_every_iter: -1
    lr: 1e-4
    save_every_epoch: 1
    #load_experiment: tests_megadepth

